### ISSUE TITLE
Add support for Groovy annotation

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#10]

**Comment by hadim** [comment]
Need to be fixed in the `scripting-groovy` package.

**Comment by hadim** [comment]
Since Scijava kernel will be run from Fiji/ImageJ, the need for annotations such as `Grab` is less important. I will downgrade the priority of this issue.

**Comment by ctrueden** [comment]
I actually think some dependency bootstrapping mechanism is super important. It would actually be nice if it were agnostic to the language, but the Groovy-specific `@Grab` is better than nothing.

Requiring users to install ImageJ or Fiji in order to use SciJava stuff is, IMHO, bad. One of the beautiful things about the notebook to me is that you can just open a `.ipynb` file and go—no need to install any other crap. (That's one thing I'll miss about classic Beaker, BTW: the ease of installation. Installing Jupyter is still a PITA by comparison.)

**Comment by hadim** [comment]
There are multiple points here : 

1. A language agnostic bootstrapping mechanism would be really great indeed. I guess we could re-use the Scijava annotation mechanism with something like that : 

```groovy
// @GrabResolver name='imagej', root='http://maven.imagej.net/content/groups/public/'
// @Grab 'net.imagej:imagej:2.0.0-rc-58'
```
or similar. With this, the support for Groovy annotation is definitely a low priority.

2. I get your point on the kernel being independent on Fiji and it really makes sense to me now you say it. For now the kernel is installed from within Fiji and so is setup to use the Java used to execute Fiji (and the associated classpath, [see here for code](https://github.com/hadim/scijava-jupyter-kernel/blob/360aaf3fbb54063ac06938b083e99360385e5a20/src/main/java/org/scijava/jupyter/utils/JupyterUtil.java#L32)).

But once we have a language agnostic bootstrapping mechanism, we could definitely get rid of the need of Fiji. And even create a conda package of the scijava kernel that depend on the Java conda package. Then will only have to install the Anaconda distribution, then execute `conda install notebook scijava-jupyter-kernel` and will be able to run any notebook file made for a scijava kernel. That would be awesome !

3. Jupyter is easy to install if you use the Anaconda distribution : https://www.continuum.io/downloads :-)

**Comment by ctrueden** [comment]
> Jupyter is easy to install if you use the Anaconda distribution

```
$ brew cask install anaconda
==> Caveats
To use anaconda, you may need to add the ~/anaconda3/bin directory
to your PATH environment variable, eg (for bash shell):

  export PATH=~/anaconda3/bin:"$PATH"

==> Satisfying dependencies
complete
==> Downloading https://repo.continuum.io/archive/Anaconda3-4.3.1-MacOSX-x86_64.sh
######################################################################## 100.0%
==> Verifying checksum for Cask anaconda
==> Running installer script Anaconda3-4.3.1-MacOSX-x86_64.sh
==> PREFIX=/Users/curtis/anaconda3
==> installing: python-3.6.0-0 ...
...
==> installing: jupyter-1.0.0-py36_3 ...
==> installing: jupyter_client-4.4.0-py36_0 ...
==> installing: jupyter_console-5.0.0-py36_0 ...
==> installing: jupyter_core-4.2.1-py36_0 ...
...
==> installation finished.
🍺  anaconda was successfully installed!
$ which jupyter
/usr/local/bin/jupyter
$ ls -la /usr/local/bin/jupyter
-rwxr-xr-x  1 curtis  admin  241 Aug  8  2016 /usr/local/bin/jupyter*
$ jupyter --version
4.1.0
$ anaconda3/bin/jupyter --version
4.2.1
```
So I guess I have two versions of Jupyter now... and I have no idea what I even did last August to install the 4.1.0 version... *sigh*

**Comment by hadim** [comment]
`which jupyter` should tell you where the jupyter file is and then you should be able to remove the associated anaconda folder.

**Comment by hadim** [comment]
Oh I didn't see the `which jupyter` command you've executed.

I guess you used `pip install jupyter` for the first version you have. Just uninstall it with `pip` and everything should be fine.

**Comment by ctrueden** [comment]
Heh, I guess I had yet a third jupyter installed with pip:
```
$ pip uninstall jupyter
Uninstalling jupyter-1.0.0:
  /usr/local/lib/python2.7/site-packages/jupyter-1.0.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/site-packages/jupyter-1.0.0.dist-info/INSTALLER
  /usr/local/lib/python2.7/site-packages/jupyter-1.0.0.dist-info/METADATA
  /usr/local/lib/python2.7/site-packages/jupyter-1.0.0.dist-info/RECORD
  /usr/local/lib/python2.7/site-packages/jupyter-1.0.0.dist-info/WHEEL
  /usr/local/lib/python2.7/site-packages/jupyter-1.0.0.dist-info/metadata.json
  /usr/local/lib/python2.7/site-packages/jupyter-1.0.0.dist-info/pbr.json
  /usr/local/lib/python2.7/site-packages/jupyter-1.0.0.dist-info/top_level.txt
  /usr/local/lib/python2.7/site-packages/jupyter.py
  /usr/local/lib/python2.7/site-packages/jupyter.pyc
Proceed (y/n)? y
  Successfully uninstalled jupyter-1.0.0
$ which jupyter
/usr/local/bin/jupyter
```
Thanks for the idea, though. I won't worry about it for now, since it probably won't hurt anything.

**Comment by hadim** [comment]
ahah ! A classic. In the future only use conda for Python libs installation and everything will be fine.

To get latest update you can also enable conda-forge : `conda config --add channels conda-forge && conda update --all`

**Comment by hadim** [comment]
I am closing here in favor of #28.
