### ISSUE TITLE
Reuse / Fork base Jupyter JVM kernel

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#14]
Such as https://github.com/twosigma/beaker-notebook-private/tree/master/kernel/base/src/main/java/com/twosigma

Or the potentially future base implementation from https://groups.google.com/forum/#!topic/jupyter/O1KnaEPqCM4

**Comment by ctrueden** [comment]
So, [this just happened](https://github.com/twosigma/beakerx): Beaker is now a set of JVM extensions for Jupyter. This might be a very good thing for our project...

**Comment by hadim** [comment]
Very good news. Looks like they are also going to re-use the following https://github.com/jupyter/jvm-repr

See here for details : https://groups.google.com/forum/#!topic/jupyter/OaaqlsuMaWM

**Comment by hadim** [comment]
Here is what we want to fork/re-use : https://github.com/twosigma/beakerx/tree/master/kernel/base/src/main/java/com/twosigma/jupyter

**Comment by hadim** [comment]
`master` now uses the BeakerX base kernel. Code can't be executed yet since [`Evaluator`](https://github.com/hadim/scijava-jupyter-kernel/blob/master/src/main/java/org/scijava/jupyter/evaluator/DefaultEvaluator.java) is not implemented. I am working on it !
