### ISSUE TITLE
Add to the list of Jupyter Kernels

### ISSUE THREAD

**Issue by blink1073** [hadim/scijava-jupyter-kernel#30]
Is this ready to be added to this list: https://github.com/jupyter/jupyter/wiki/Jupyter-kernels?

**Comment by hadim** [comment]
I will soon. I would like to get some stuff done first.

**Comment by hadim** [comment]
Will do after #1 and # 32 are done.

**Comment by hadim** [comment]
Done

**Comment by blink1073** [comment]
Nice!
