### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#32]
Hi @ctrueden ,

I need you on this ! And I think it should be easy to solve with your Maven skills :-)

I am creating a [conda recipe](https://conda.io/docs/building/recipe.html) (see it as a Travis-like mechanism that output a nice package that can be then distributed and installed with `conda`).

The package is built in an isolated environment with only jupyter, maven and openjdk (I want the conda package to be totally ImageJ-independent since ImageJ integration is made directly within ImageJ).

So my idea is to "install" (copy scijava-jupyter-kernel jar and its dependencies) to a specific folder, probably something like `$PREFIX/opt/scijava-jupyter-kernel`. And then at the end of the package installation, I run some Java-glue-code to install all the kernels.

Now my question is : how to tell Maven I want to copy all the required jars somewhere ? For this, I don't want to modify the scijava-jupyter-kernel `pom.xml` (since conda build is very specific) but instead, I am using a `settings.xml` file in the conda recipe folder.

Note the recipe won't live in the `scijava-jupyter-kernel` but will live in a separated git repo on the `conda-forge` GitHub organization.

**Comment by hadim** [comment]
Here is the recipe : https://github.com/conda-forge/staged-recipes/pull/2841

**Comment by hadim** [comment]
For now I am using `imagej.app.directory`, that seems to do the job. Let me know if there is another way.

**Comment by hadim** [comment]
Recipe submitted https://github.com/conda-forge/staged-recipes/pull/2841

Waiting for approval.

**Comment by hadim** [comment]
Done

**Comment by ctrueden** [comment]
You can use `mvn dependency:copy-dependencies` to place all dependencies into the `target/dependency` folder. And then from there, copy them wherever you want. This would be a little less hacky than using the scijava-maven-plugin's copy-jars goal. I assume that as things stand, the JARs end up in `${env.PREFIX}/opt/scijava-jupyter-kernel/jars`? Is that where you want them to end up? If so, I guess you can just stick with the copy-jars goal.

**Comment by hadim** [comment]
Great I think I'll use `mvn dependency:copy-dependencies` and then just move the files where I want.

It doesn't really matter where I put the them. `/opt` is an arbitrary choice.

The conda repo has been created https://github.com/conda-forge/scijava-jupyter-kernel-feedstock and builds should be generated soon.

**Comment by ctrueden** [comment]
You might be able to avoid the after-the-fact copy too, by [setting the `outputDirectory` property](https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html#outputDirectory) of the mojo.
