### ISSUE TITLE
Fiji packaging

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#35]
@ctrueden , would you consider integrating this repo to `scijava` and so integrate it by default into Fiji ?

I have created a Fiji menu where people can easily install a kernel linked to their Fiji distribution. That is a nice feature waiting for https://github.com/hadim/scijava-jupyter-kernel/issues/28.

And it is also required for the long term tight-integration feature : https://github.com/hadim/scijava-jupyter-kernel/issues/11 (this one requires some work on the Jupyter side).

I could create an update-site but to be honest I don't really want to... those are painful to maintain :-(

**Comment by ctrueden** [comment]
> would you consider integrating this repo to scijava and so integrate it by default into Fiji ?

Sure, I will have to review what that would entail.

> I could create an update-site but to be honest I don't really want to... those are painful to maintain :-(

A huge (some might say insane) amount of effort has gone into making update sites as easy as possible for non-techie users to use and maintain. E.g., the full-featured command line updater. So you can go ahead and cry me a river. It would be more constructive to explain _why_ you find them painful, so that the problems can perhaps be addressed.

**Comment by hadim** [comment]
Also I think I am going to reuse some of the code in `imagej-notebook`. I'll probably merge the code into the this repo and wait to have something more stable before make a separated repo.

**Comment by hadim** [comment]
Sorry for the not very constructive argument about update site. I tried to automate the update site upload process with Travis but I often have some conflicts when the Fiji used is not updated. I don't remember the Travis job. I'll post it here later.

Update sites are awesome for end users and "manual uploaders". I just found it hard to automate its usage.

**Comment by hadim** [comment]
I propose we start talking about merging this repo in the `scijava` org after some big features are working (probably not before few weeks).

- #28 
- #7 
- #37 
- #21

**Comment by hadim** [comment]
Let's not worry about that for now.

**Comment by ctrueden** [comment]
I would be happy to transfer it over to the scijava org any time, and set you as the admin. It would be more consistent with the rest of the core components to do that. But I am OK with leaving it in your GitHub space if you feel strongly otherwise.

**Comment by hadim** [comment]
I am ok with that. See #60.

Let's do that in few weeks when I'll have more time.
