### ISSUE TITLE
Polyglot kernel

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#43]
Consider making the kernel polyglot.

Choose a default language (Python or Groovy) and let the user choose languages per cell.

That would require some refactoring on the kernel side but nothing too complicated.

Before starting the implementation, we need an UI on the Jupyter client side to let the user easily choose what language he wants. Such a feature are not ready yet but definitively coming soon in Jupyter Lab.

**Comment by hadim** [comment]
For the implementation, we can just add a level of abstraction in between `ScijavaEvaluator` and `Worker`.

**Comment by imagejan** [comment]
@hadim 
> we need an UI on the Jupyter client side

We could avoid the UI dependency if using an annotation, similar to the scijava parameters, such as:

```
#!python
# @ImgPlus img
```

or

```
#!groovy
// @ImgPlus img
```

What do you think?

**Comment by hadim** [comment]
Yes. That is also a possibility.

**Comment by hadim** [comment]
Ok, so even if I still don't see the point of running different languages in the same notebook, I can clearly see the advantages​ of turning this kernel in a meta kernel.

In term of design it makes a lot of sense since all the supported languages are executed trought the same code base.

It will also be more convenient to have only one single kernel to manage for the dev team and also less confusing for the users. 

I like the shebang style you've proposed @imagejan and we won't have to wait for the Jupyter team to develop the UI we need.

An important question is what default language do we want to have ?

I think Groovy is a safe choice since is more Java like than Python and widely used.

Let me know what you guys think about that. I don't want to start implementing it without having your thoughts about it.

**Comment by hadim** [comment]
See #46 for an implementation of the idea.

**Comment by ctrueden** [comment]
Thank you very much for working on this, @hadim.

Yes, I think Groovy is the best choice for default language. It is very well-implemented—dare I say more polished and less buggy than Jython is, in my experience.

FYI, ideally, I need to update all [ImageJ tutorial Beaker notebooks](https://github.com/imagej/tutorials) to use the new SciJava Jupyter kernel before mid-June, in time for the [DAIS Learnathon](http://forum.imagej.net/t/fiji-ij2-knime-learnathon-2017-intense-7-day-developer-training-apply-now-or-regret-later/5159?u=ctrueden). I'm still chugging away on my backlog of maintainer stuff—almost done now! That includes reviewing the SciJava Grape service, which I plan to split into a new SciJava component. I am (naively?) hoping we can get a first stable release of the scijava-jupyter-kernel and then I can convert the Beaker notebooks over, and use them during the Learnathon. If that plan ends up being too ambitious, though, then I can just have people use Beaker 1.x again for now.

**Comment by hadim** [comment]
In fact, I was waiting for you to be able to release a 1.0.0 :-)

I want to have the Grape Service before releasing and make the announcement of the kernel.

I also need to a Scijava release to be able to merge the autocompletion PR (https://github.com/hadim/scijava-jupyter-kernel/pull/31).

About the tutorials, you might want to have a look at this PR https://github.com/imagej/tutorials/pull/37.

I should be able to work on it this weekend if you can merge the Grape Service and release a Scijava version.

I am super excited that your guys are planning to use it for the Learnathon!

**Comment by ctrueden** [comment]
> In fact, I was waiting for you to be able to release the 1.0.0 :-)

I know, I'm sorry for being slow.

> About the tutorials, you might want to have a look at this PR imagej/tutorials#37.

Thanks for the reminder—that's great. My plan was to get the scijava-jupyter-kernel going on my machine, try the converted notebooks, and if things seem OK then merge it ASAP afterward.

> I should be able to work on it this weekend if you can merge the Grape Service and release a Scijava version before that.

I have to do some more urgent things today, so unfortunately may not have the `GrapeService` and SJC release ready today. 😞  But will keep working on it ASAP.

> I am super excited that your guys are planning to use it for the Learnathon!

Yeah! 😀
