### ISSUE TITLE
Kernel dies when using #! syntax on Windows

### ISSUE THREAD

**Issue by imagejan** [hadim/scijava-jupyter-kernel#49]
On Windows, it seems that any use of the shebang (#!) syntax to select the language leads to a blocked kernel.
When run with `jupyter notebook`, there's an error message that the kernel died. When running with `jupyter lab`, the kernel stay in "restarting" state forever (i.e. it seemed to work fine at start, and gets restarted as soon as you run a cell with `#!python`, `#!groovy` or some such).

(tested with version 0.3.0-0 from conda-forge)

**Comment by hadim** [comment]
I was using `System.getProperty("line.separator")` to detect the first line with the shebang but it appears that Jupyter notebook returns string with `\n` for new line (this is why it works on Linux).

That should fix it : https://github.com/hadim/scijava-jupyter-kernel/commit/a09ee524fd1955a7d5a89ed6a9805210ead2582d

**Comment by hadim** [comment]
@imagejan would you mind testing it? Just replace your current kernel jar file by the one: https://drive.google.com/open?id=0Bwt2y0cMI-oyYjZPUEJOUlA2blU

You'll find the file under `PATH_TO_CONDA/envs/java/opt/scijava-jupyter-kernel` (work on Linux, OSX and Windows).

**Comment by hadim** [comment]
Once you confirm me it's working. I'll release a new version.

**Comment by imagejan** [comment]
👍 Great! I just tested 0.3.1-SNAPSHOT and confirm that it's working now.

**Comment by hadim** [comment]
Awesome. I'll release 0.3.1 today.

**Comment by hadim** [comment]
Linux and OSX package for 0.3.1 are available on conda forge. (Windows should follow soon).
