### ISSUE TITLE
Shebang syntax conflicts with script parameters

### ISSUE THREAD

**Issue by imagejan** [hadim/scijava-jupyter-kernel#51]
Consider the following cell contents:

```groovy
#!groovy
// @LogService log
log.info("Hello, World!")
```

This will throw:

```
javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: log for class: Script1
```

SciJava script parameters are required to be at the very beginning of the script.
Maybe the shebang (`#!groovy`) line can be stripped from the script before handing it to the ScriptService to allow proper input harvesting?

(Tested with scijava-jupyter-kernel 0.3.1-0 on Windows.)

**Comment by hadim** [comment]
I can't reproduce the bug. The script works for me as excepted because the shebang line is removed before being sent to the standard Scijava scripting mechanism.

**Comment by hadim** [comment]
In fact I can reproduce it on Windows (not on Linux). Weird...

**Comment by hadim** [comment]
It does not seem to be related to shebang because I still have the issue without it on Windows. Can you confirm that ?

**Comment by hadim** [comment]
I close in favor of #53.

**Comment by imagejan** [comment]
@hadim 
> It does not seem to be related to shebang because I still have the issue without it on Windows. Can you confirm that ?

No, this works fine for me:
```groovy
// @LogService log
log.error("Hey there!")
```

It outputs:
```
[ERROR] Hey there!

Out[1]: null
```

**Comment by hadim** [comment]
It does not for me.... Now I am very confused :-(

Do you see an error message in the console?

**Comment by imagejan** [comment]
See my comment in #53, can you check if they work in the very first cell?

**Comment by hadim** [comment]
Ok let's discuss on #53

**Comment by ctrueden** [comment]
Quick related question about the shebang: would it help for the SciJava script framework itself to support the shebangs? I think this would be a desirable feature. Right now, to tell the script service to run a script, you must pass a faux file path from which the extension is extracted and from which the language is decided. The shebang approach would be less roundabout.

If you guys agree, I can look into adding the shebang feature to SciJava scripting core.

**Comment by hadim** [comment]
I think that is a good idea but what about the scripts that does not have shebang? You can't set a default language or you will have a big backward incompatibility issue.

**Comment by imagejan** [comment]
@ctrueden Yes, would be great if the ScriptService supports both running with a file extension-defined language, and - when called like `scriptService.run(script)` - with the shebang syntax if there's no other hint.
