### ISSUE TITLE
Empty scripts cause kernel death

### ISSUE THREAD

**Issue by imagejan** [hadim/scijava-jupyter-kernel#52]
Cells containing nothing but the shebang language declaration (and a newline):

```groovy
#!groovy

```

will cause the kernel to die.

**Comment by hadim** [comment]
Should be fixed now. Once you confirm me that with https://drive.google.com/open?id=0Bwt2y0cMI-oyV1dxdjEwMDdya2c, I'll close here.

**Comment by imagejan** [comment]
Great, I confirm this fixed it! 👍
