### ISSUE TITLE
Shebang syntax conflicts with script parameters on Windows

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#53]
See https://github.com/hadim/scijava-jupyter-kernel/issues/51 for the details.

**Comment by imagejan** [comment]
They _do_ work for me unless I use a shebang language declaration in the beginning... 😟

**Comment by imagejan** [comment]
Oh wait, it seems as if script parameters only work in the _very first_ cell of a notebook.

**Comment by hadim** [comment]
Can you confirm it's not related to shebang ?

**Comment by imagejan** [comment]
So, I tested more carefully, here's what I have:

![image](https://cloud.githubusercontent.com/assets/2033938/26113906/27dff894-3a5c-11e7-87c7-edc542ba0eea.png)

(I was running each cell one after the other, without changing order or re-running previous cells.)

**Comment by hadim** [comment]
Cell 1 does not even work for me on Windows. I am lost :-)

Can you copy paste me the following commands : `conda info` and `conda list` ?

**Comment by imagejan** [comment]
```
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.21.6
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3\envs\scijava
       envs directories : C:\Anaconda3\envs
          package cache : C:\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\cygwin\home\eglijan\.condarc
           offline mode : False
```

```
# packages in environment at C:\Anaconda3\envs\scijava:
#
backports.shutil_get_terminal_size 1.0.0                    py27_1    conda-forg
e
backports_abc             0.5                      py27_0    conda-forge
bleach                    1.5.0                    py27_0    conda-forge
certifi                   2017.4.17                py27_0    conda-forge
colorama                  0.3.7                    py27_0    conda-forge
configparser              3.5.0                    py27_0    conda-forge
decorator                 4.0.11                   py27_0    conda-forge
entrypoints               0.2.2                    py27_1    conda-forge
enum34                    1.1.6                    py27_1    conda-forge
functools32               3.2.3.2                  py27_1    conda-forge
html5lib                  0.999                    py27_0    conda-forge
ipykernel                 4.6.1                    py27_0    conda-forge
ipython                   5.3.0                    py27_0    conda-forge
ipython_genutils          0.2.0                    py27_0    conda-forge
jinja2                    2.9.5                    py27_0    conda-forge
jsonschema                2.5.1                    py27_0    conda-forge
jupyter_client            5.0.1                    py27_0    conda-forge
jupyter_core              4.3.0                    py27_0    conda-forge
jupyterlab                0.19.0                   py27_0    conda-forge
markupsafe                0.23                     py27_1    conda-forge
mistune                   0.7.4                    py27_0    conda-forge
nbconvert                 5.1.1                    py27_1    conda-forge
nbformat                  4.3.0                    py27_0    conda-forge
notebook                  5.0.0                    py27_0    conda-forge
openjdk                   8.0.121                       0
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py27_0    conda-forge
pathlib2                  2.2.1                    py27_0    conda-forge
pickleshare               0.7.3                    py27_0    conda-forge
pip                       9.0.1                    py27_0    conda-forge
prompt_toolkit            1.0.14                   py27_0    conda-forge
pygments                  2.2.0                    py27_0    conda-forge
python                    2.7.12                        2    conda-forge
python-dateutil           2.6.0                    py27_0    conda-forge
pyzmq                     16.0.2                   py27_1    conda-forge
scandir                   1.5                      py27_1    conda-forge
scijava-jupyter-kernel    0.3.1                         0    conda-forge
setuptools                33.1.1                   py27_0    conda-forge
simplegeneric             0.8.1                    py27_0    conda-forge
singledispatch            3.4.0.3                  py27_0    conda-forge
six                       1.10.0                   py27_1    conda-forge
ssl_match_hostname        3.5.0.1                  py27_1    conda-forge
testpath                  0.3                      py27_0    conda-forge
tornado                   4.5.1                    py27_0    conda-forge
traitlets                 4.3.2                    py27_0    conda-forge
vs2008_runtime            9.00.30729.5054               0
wcwidth                   0.1.7                    py27_0    conda-forge
webencodings              0.5                      py27_0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
win_unicode_console       0.5                      py27_0    conda-forge
wincertstore              0.2                      py27_0    conda-forge
```

**Comment by hadim** [comment]
Thank you @imagejan.

The major difference is that Jupyter is used with Python 2.7 on your system and Python 3.6 on mine. So I tried with Python 2.7 and I still can't execute the cell 1.

**Comment by hadim** [comment]
I don't understand this issue...

`info.inputs()` returns nothing on Windows : https://github.com/hadim/scijava-jupyter-kernel/blob/master/src/main/java/org/scijava/jupyter/kernel/evaluator/Worker.java#L99

**Comment by hadim** [comment]
On my system, apparently, it works on @imagejan system (beside the shebang issue).

**Comment by hadim** [comment]
I am an idiot... I kept forgetting the `@` character the whole day... of course, it didn't work.

It's working now for me, even with the shebang at the first line. Can you try this package @imagejan please: https://drive.google.com/open?id=0Bwt2y0cMI-oyMDA2Zm9zTk8wNmc ?

Sorry for the mess :-(

**Comment by hadim** [comment]
0.3.2 is released and should hit conda forge soon.

I'll close here, feel free to re-open if needed.

**Comment by imagejan** [comment]
No need to apologize, I'm really excited about this work!

I just tested with version 0.3.2-0, and I still get problems with combining `#!` and scijava parameters:

![image](https://cloud.githubusercontent.com/assets/2033938/26144205/37197ede-3ae8-11e7-8e93-565ebe52c7aa.png)

**Comment by hadim** [comment]
Can you send me your notebook file please ?

**Comment by imagejan** [comment]
Here you are:
[TestNotebook.zip](https://github.com/hadim/scijava-jupyter-kernel/files/1007441/TestNotebook.zip)

**Comment by hadim** [comment]
Thanks. Is it happening only on Windows ?

**Comment by imagejan** [comment]
Yes, I just tested the same file on Mac OSX, where all cells show the expected log output.

**Comment by hadim** [comment]
Just tested your notebook on a new conda env on Windows 10 and I can't reproduce the issue... Do you see any error message in the console?

**Comment by imagejan** [comment]
Strange. The contents of my console (the basic Windows 7 Command Prompt) after running the **first two** cells one after each other are a lot of white space and no informative message really:

```



























































































                              [INFO] Script Language for 'python' found. to use.






































































































NFO] Script Language for 'python' found. to use.





































































































                              [AWT-EventQueue-0] INFO com.twosigma.beaker.jupyte
r.msg.MessageCreator - Execution result ERROR: Traceback (most recent call last)
:
```

**Comment by imagejan** [comment]
(The same when running Windows Powershell)

When running cell [4], I get the error below on the console. I wonder if this interferes with a previous beaker installation I have?! Would you expect this `com.twosigma.beaker.jupyter.msg.MessageCreator`?

```
                              [AWT-EventQueue-0] INFO com.twosigma.beaker.jupyter.msg.MessageCreator - Execution result
ERROR: Traceback (most recent call last):
[AWT-EventQueue-0] INFO com.twosigma.beaker.jupyter.msg.MessageCreator - Execution result ERROR: javax.script.ScriptExce
ption: groovy.lang.MissingPropertyException: No such property: log4 for class: Script2
```

**Comment by hadim** [comment]
The ton of white spaces is due to the console. It does not happen using the git bash console.

The `MessageCreator` error is excepted when the code raises an error. It's gonna be hard for me to debug this if I can't reproduce the bug...

The other major difference is that I am using Windows 10. It's unlikely to be this but you can easily test it on a Windows 10 system so we are sure.

Also, try to re-install Anaconda to see if it's related with some weird conflict with previous version.

**Comment by imagejan** [comment]
Hm, for me it still doesn't work, neither on Git Bash nor on another bash.exe installation I have. Will investigate more, and also try on a different machine when I find the time.
Thanks for all your efforts!

**Comment by imagejan** [comment]
I just tested on a different system (with Windows 10) and can't reproduce the issue. Let's close the issue for now (I can't because you opened it), and reopen only if it reappears on any other machine.

Sorry for the trouble caused, and thanks for all your help.

With the introduction of the new `#@` syntax by @ctrueden this issue might be moot anyways.

**Comment by hadim** [comment]
Ok.
