### ISSUE TITLE
Rich output

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#7]
Display complex output such as images, lists, dict, etc nicely using Jupyter widgets.

**Comment by hadim** [comment]
It's easy to return images (encoded in base64) or html. The question is when to do that ?

It depends on the `Object` returned by the execution and so it depends the languages. So that should be decided by languages.

**Comment by hadim** [comment]
We definitely want to use this kind of library : https://github.com/jupyter/jvm-repr (not mature enough yet)

**Comment by hadim** [comment]
For this I need to understand better how Beaker handle outputs.

**Comment by hadim** [comment]
Use this as a starting point : https://github.com/twosigma/beakerx/issues/5120#issuecomment-295231169

**Comment by hadim** [comment]
I am gonna wait that Beakerx add support for jvm-repr.

**Comment by hadim** [comment]
See WIP in #36

**Comment by hadim** [comment]
`NotebookService` is a scijava service and should stay like that in my opinion. But we obviously want to have methods to display IJ2 images type (`RAI` for example). And this code should reside into `net.imagej` or `net.imglib2`, so not here.

The question is how to do that nicely ?

Ideally I want to keep things simple for the user so he has only one service to import : `NotebookService`.

So I need to find a way to dynamically add methods to `NotebookService` at runtime. For example a `note.imagej` package could have a `ImageJNotebookService` class that would discovered by `DefaultNotebookService`.

I don't even know if it's possible. But I have the feeling something similar can be achieve by Scijava :-)

**Comment by hadim** [comment]
See here the possibilities for now : https://gist.github.com/hadim/e2d440407f0e26c4dcef90fa3456dde5

**Comment by hadim** [comment]
Also I need to find a way to convert `Img` or similar type to png/jpeg.

**Comment by imagejan** [comment]
> to convert Img or similar type to png/jpeg

[`DefaultNotebookService.display()`](https://github.com/imagej/imagej-notebook/blob/f1139f2c4e55e387c75949e8691fe56adb469ca8/src/main/java/net/imagej/notebook/DefaultNotebookService.java#L83-L123) is returning a `net.imglib2.display.screenimage.awt.ARGBScreenImage`. Does that help in any way?

**Comment by hadim** [comment]
Yes I saw that but then how do I convert it to PNG/JPEG ?

To display images I need to return an image mimetype with the image data as a base64 string. Or whatever our modern browser support.

**Comment by hadim** [comment]
Those methods are great : https://github.com/imagej/imagej-notebook/blob/f1139f2c4e55e387c75949e8691fe56adb469ca8/src/main/java/net/imagej/notebook/DefaultNotebookService.java#L83-L123

But I still need to get a base64 data string in order to display them (I think...).

See the Beakerx code that display images : https://github.com/twosigma/beakerx/blob/ec1f94746399c27fcf48f64e6d0ae4f2fddde8be/kernel/base/src/main/java/com/twosigma/beaker/mimetype/ImageContainer.java

**Comment by hadim** [comment]
See #38 now.

**Comment by ctrueden** [comment]
I made some related comments [here](https://github.com/scijava/scijava-common/pull/265#issuecomment-296701387).

**Comment by ctrueden** [comment]
> I need to find a way to convert Img or similar type to png/jpeg.

That is almost exactly what `NotebookService.display` does: [`RandomAccessibleInterval` in](https://github.com/imagej/imagej-notebook/blob/imagej-notebook-0.2.1/src/main/java/net/imagej/notebook/DefaultNotebookService.java#L84), and [`BufferedImage` out](https://github.com/imagej/imagej-notebook/blob/imagej-notebook-0.2.1/src/main/java/net/imagej/notebook/DefaultNotebookService.java#L123).

**Comment by hadim** [comment]
Yes, I saw that. I am trying to figure out if it's possible to display this directly into the notebook of it needs to be converted again.

**Comment by hadim** [comment]
A small piece of cide did the trick : 

```java
// Convert to PNG
        final ByteArrayOutputStream os = new ByteArrayOutputStream();
        try {
            ImageIO.write(target.image(), "PNG", os);
        } catch (IOException ex) {
            log.error(ex);
        }
        return Base64.getEncoder().encodeToString(os.toByteArray());
```

I have some scaling issue but nothing to worry about too much.

**Comment by ctrueden** [comment]
> I have some scaling issue

Yeah, in general this gets really tricky, especially when images are >8-bit. We can make a "best effort" but it might be better if ultimately, the image display widget in the notebook had some sort of built-in min/max adjuster thing. Because we won't be able to get it right in 100% of cases.

**Comment by hadim** [comment]
For now, I am focusing on the server side but having a Jupyter widget to display images allowing to modify contrast settings would be really nice. 

In the meantime, people can still display images with the IJ1 interface (not super nice for sharing notebooks...)

**Comment by hadim** [comment]
(and ultimately the secret goal is to create an IJ interface as Jupyter Lab extension :-))

**Comment by hadim** [comment]
#40 has been merged and is the foundation os the rich output mechanism of the kernel.

At the moment the kernel has `net.imagej` classes but on the mid-term, those classes will be moved to the `imagej-notebook` repo.

**Comment by hadim** [comment]
I close here. Feel free to comment here or on a new issue.

**Comment by hadim** [comment]
By the way, more I use Scijava, more I found it awesome in term of coding standard, usability, and extensibility. Great job!
