### ISSUE TITLE
Build fails with repo2docker - Unable to locate package openjdk-11-jdk

### ISSUE THREAD

**Issue by psychemedia** [hadim/scijava-jupyter-kernel#93]
Trying to launch a version of this kernel locally using `repo2docker` gives an error trying to find the OpenJDK package: 

```
E: Unable to locate package openjdk-11-jdk
Removing intermediate container 331568536f3c
The command '/bin/sh -c apt-get update && apt-get install --yes --no-install-recommends openjdk-11-jdk maven && apt-get purge && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by ctrueden** [comment]
The scijava-jupyter-kernel project is being retired in favor of other solutions like [IJava](https://github.com/SpencerPark/IJava) and [BeakerX](http://beakerx.com).
